export interface WptQuestion {
  id: number;
  question: string;
  type: 'pilihan_ganda' | 'ya_tidak' | 'isian';
  options?: string[];
  optionImages?: string[];
  correctAnswer: string;
  category: string;
  image?: string;
}

export const wptQuestions: WptQuestion[] = [
  {
    id: 1,
    question: 'Bulan lalu pada awal tahun ini adalah:',
    type: 'pilihan_ganda',
    options: ['Januari', 'Maret', 'Juli', 'Desember', 'Oktober'],
    correctAnswer: '4',
    category: 'Logika',
  },
  {
    id: 2,
    question: 'MENANGKAP adalah lawan kata dari:',
    type: 'pilihan_ganda',
    options: ['meletakkan', 'membebaskan', 'beresiko', 'berusaha', 'turun tingkat'],
    correctAnswer: '2',
    category: 'Vocab',
  },
  {
    id: 3,
    question: 'Sebagian besar hal di bawah ini serupa satu sama lain. Manakah salah satu di antaranya yang kurang serupa dengan yang lain?',
    type: 'pilihan_ganda',
    options: ['Januari', 'Agustus', 'Rabu', 'Oktober', 'Desember'],
    correctAnswer: '3',
    category: 'Logika',
  },
  {
    id: 4,
    question: "Apakah RSVP berarti 'jawablah yang tidak perlu'?",
    type: 'ya_tidak',
    correctAnswer: 'TIDAK',
    category: 'Pengetahuan',
  },
  {
    id: 5,
    question: 'Dalam kelompok kata berikut, manakah kata yang berbeda dari kata yang lain?',
    type: 'pilihan_ganda',
    options: ['pasukan', 'liga', 'berpartisipasi', 'pak', 'kelompok'],
    correctAnswer: '3',
    category: 'Logika',
  },
  {
    id: 6,
    question: 'BIASA adalah lawan kata dari:',
    type: 'pilihan_ganda',
    options: ['jarang', 'terbiasa', 'tetap', 'berhenti', 'selalu'],
    correctAnswer: '1',
    category: 'Vocab',
  },
  {
    id: 7,
    question: 'Gambar manakah yang terbuat dari dua gambar di dalam tanda kurung { ◁ △ }?',
    type: 'pilihan_ganda',
    options: ['Gambar 1', 'Gambar 2', 'Gambar 3', 'Gambar 4', 'Gambar 5'],
    optionImages: [
      '/wpt-images/q7_1.png',
      '/wpt-images/q7_2.png',
      '/wpt-images/q7_3.png',
      '/wpt-images/q7_4.png',
      '/wpt-images/q7_5.png',
    ],
    correctAnswer: '3',
    category: 'Visual',
    image: '/wpt-images/q7.png',
  },
  {
    id: 8,
    question: 'Perhatikan urutan angka berikut. Angka berapa yang selanjutnya muncul?\n8  4  2  1  ½  ¼  ......',
    type: 'isian',
    correctAnswer: '1/8',
    category: 'Deret',
  },
  {
    id: 9,
    question: 'Klien – Pelanggan. Apakah kata-kata ini:',
    type: 'pilihan_ganda',
    options: ['memiliki arti yang sama', 'memiliki arti berlawanan', 'tidak memiliki arti sama atau berlawanan'],
    correctAnswer: '1',
    category: 'Vocab',
  },
  {
    id: 10,
    question: 'Manakah kata berikut yang berhubungan dengan AROMA saat gigi mengunyah?',
    type: 'pilihan_ganda',
    options: ['manis', 'bau tak sedap', 'bau wangi', 'hidung', 'bersih'],
    correctAnswer: '1',
    category: 'Vocab',
  },
  {
    id: 11,
    question: 'MUSIM GUGUR adalah lawan dari:',
    type: 'pilihan_ganda',
    options: ['liburan', 'musim panas', 'musim semi', 'musim dingin', 'musim gugur'],
    correctAnswer: '3',
    category: 'Vocab',
  },
  {
    id: 12,
    question: 'Sebuah pesawat terbang 300 kaki dalam ½ detik. Pada kecepatan yang sama berapa kaki ia terbang dalam 10 detik?',
    type: 'isian',
    correctAnswer: '6000',
    category: 'Aritmatika',
  },
  {
    id: 13,
    question: 'Anggaplah dua pernyataan pertama adalah benar. Apakah yang terakhir:\n\nAnak-anak lelaki ini adalah anak yang normal. Semua anak normal sifatnya aktif. Anak-anak lelaki ini aktif.',
    type: 'pilihan_ganda',
    options: ['benar', 'salah', 'tidak tahu'],
    correctAnswer: '1',
    category: 'Logika',
  },
  {
    id: 14,
    question: 'JAUH adalah lawan kata dari:',
    type: 'pilihan_ganda',
    options: ['terpencil', 'dekat', 'jauh', 'terburu-buru', 'pasti'],
    correctAnswer: '2',
    category: 'Vocab',
  },
  {
    id: 15,
    question: '3 permen lemon seharga 10 rupiah. Berapa harga ½ lusin?',
    type: 'isian',
    correctAnswer: '20',
    category: 'Aritmatika',
  },
  {
    id: 16,
    question: 'Berapa banyak duplikasi yang sama dari lima pasangan angka di bawah ini?',
    type: 'isian',
    correctAnswer: '2',
    category: 'Deret',
    image: '/wpt-images/q16.png',
  },
  {
    id: 17,
    question: 'Misalkan Anda menyusun kata-kata berikut sehingga menjadi pernyataan yang benar. Lalu tuliskan huruf terakhir dari kata terakhir sebagai jawaban:\n\nSelalu – sebuah – kata kerja – kalimat – suatu – memiliki',
    type: 'isian',
    correctAnswer: 'A',
    category: 'Logika',
  },
  {
    id: 18,
    question: 'Anak lelaki berumur 5 tahun dan saudara perempuannya dua kali lebih tua. Ketika anak lelaki itu berumur 8 tahun, berapa umur saudara perempuannya?',
    type: 'isian',
    correctAnswer: '13',
    category: 'Aritmatika',
  },
  {
    id: 19,
    question: 'ITS – ITS. Apakah kata ini:\n\n1. memiliki arti yang sama\n2. memiliki arti berlawanan\n3. tidak memiliki arti sama atau berlawanan',
    type: 'pilihan_ganda',
    options: ['memiliki arti yang sama', 'memiliki arti berlawanan', 'tidak memiliki arti sama atau berlawanan'],
    correctAnswer: '3',
    category: 'Vocab',
  },
  {
    id: 20,
    question: 'Anggaplah dua pernyataan pertama adalah benar. Apakah pernyataan terakhir:\n\nJohn seusia dengan Sally. Sally lebih muda dari Bill. John lebih muda dari Bill.',
    type: 'pilihan_ganda',
    options: ['benar', 'salah', 'tidak tahu'],
    correctAnswer: '1',
    category: 'Logika',
  },
  {
    id: 21,
    question: 'Seorang dealer membeli beberapa barrel seharga 4.000 rupiah. la menjual dengan harga 5.000 rupiah, mendapat untung 50 rupiah setiap barrel. Berapa banyak barrel yang dijual?',
    type: 'isian',
    correctAnswer: '20',
    category: 'Aritmatika',
  },
  {
    id: 22,
    question: 'Misalkan Anda menyusun kata-kata berikut sehingga menjadi kalimat lengkap. Jika kalimat itu benar, tulislah (B). Jika salah, tulislah (S).\n\ntelur – menghasilkan – semua – ayam',
    type: 'isian',
    correctAnswer: 'S',
    category: 'Logika',
  },
  {
    id: 23,
    question: 'Dua dari peribahasa berikut ini memiliki arti sama. Manakah itu? (Tulis dua angka)\n1. Semakin banyak memiliki sapi, akan memiliki satu anak sapi yang buruk.\n2. Anak seperti Ayahnya.\n3. Bila tertinggal sama jauhnya dengan satu mil\n4. Seorang dikenal dari persahabatan yang dijalin\n5. Mereka adalah benih dari mangkuk yang sama',
    type: 'isian',
    correctAnswer: '1 DAN 3',
    category: 'Logika',
  },
  {
    id: 24,
    question: 'Sebuah jam terlambat 1 menit 18 detik dalam 39 hari. Berapa detik ia terlambat dalam sehari?',
    type: 'isian',
    correctAnswer: '2',
    category: 'Aritmatika',
  },
  {
    id: 25,
    question: 'CANVASS – CANVAS. Apakah kata-kata ini:',
    type: 'pilihan_ganda',
    options: ['memiliki arti yang sama', 'memiliki arti yang berlawanan', 'tidak memiliki arti sama atau berlawanan'],
    correctAnswer: '3',
    category: 'Vocab',
  },
  {
    id: 26,
    question: 'Anggaplah dua pernyataan pertama adalah benar. Pernyataan terakhir:\n\nSemua siswa mengikuti ujian. Beberapa orang di ruangan ini adalah siswa. Beberapa orang di ruangan ini mengikuti ujian.',
    type: 'pilihan_ganda',
    options: ['benar', 'salah', 'tidak tahu'],
    correctAnswer: '1',
    category: 'Logika',
  },
  {
    id: 27,
    question: 'Dalam 30 hari seorang menabung 1 dolar. Berapa rata-rata tabungannya setiap hari?',
    type: 'isian',
    correctAnswer: '1',
    category: 'Aritmatika',
  },
  {
    id: 28,
    question: 'INGENIOUS – INGENUOUS. Apakah kata-kata ini:',
    type: 'pilihan_ganda',
    options: ['memiliki arti sama', 'memiliki arti berlawanan', 'tidak memiliki arti sama atau berlawanan'],
    correctAnswer: '3',
    category: 'Vocab',
  },
  {
    id: 29,
    question: 'Dua orang menangkap 36 ikan. X menangkap 5 kali lebih banyak dari Y. Berapa ikan yang ditangkap Y?',
    type: 'isian',
    correctAnswer: '6',
    category: 'Aritmatika',
  },
  {
    id: 30,
    question: 'Sebuah kotak segi empat, yang terisi penuh memuat 800 kubik kaki gandum. Jika satu kotak lebarnya 8 kaki dan panjangnya 10 kaki, berapa kedalaman kotak itu?',
    type: 'isian',
    correctAnswer: '10',
    category: 'Aritmatika',
  },
  {
    id: 31,
    question: 'Satu angka dari rangkaian berikut tidak cocok dengan pola angka yang lainnya. Angka berapakah itu?\n½  ¼  1/6  1/8  1/9  1/12',
    type: 'isian',
    correctAnswer: '1/9',
    category: 'Deret',
  },
  {
    id: 32,
    question: "Apakah P.M. berarti 'post merediem'?",
    type: 'ya_tidak',
    correctAnswer: 'TIDAK',
    category: 'Pengetahuan',
  },
  {
    id: 33,
    question: 'DAPAT DIPERCAYA – GAMPANG PERCAYA. Apakah kata-kata ini:',
    type: 'pilihan_ganda',
    options: ['memiliki arti sama', 'memiliki arti berlawanan', 'tidak memiliki arti sama atau berlawanan'],
    correctAnswer: '2',
    category: 'Vocab',
  },
  {
    id: 34,
    question: 'Sebuah rok membutuhkan 2¼ meter kain. Berapa banyak potong yang dihasilkan dari 45 meter kain?',
    type: 'isian',
    correctAnswer: '20',
    category: 'Aritmatika',
  },
  {
    id: 35,
    question: 'Sebuah jam menunjuk tepat pada pukul 12 siang hari pada hari Senin. Pada pukul 2 siang, hari Rabu, jam itu terlambat 26 detik. Pada rata-rata yang sama, berapa banyak jam itu terlambat dalam ½ jam?',
    type: 'isian',
    correctAnswer: '0.26',
    category: 'Aritmatika',
  },
  {
    id: 36,
    question: 'Tim bisbol kami kalah 9 permainan dalam musim ini. Ini merupakan 3/8 bagian dari semua pertandingan mereka. Berapa banyak pertandingan yang mereka mainkan dalam musim kompetisi saat ini?',
    type: 'isian',
    correctAnswer: '24',
    category: 'Aritmatika',
  },
  {
    id: 37,
    question: 'Apakah angka selanjutnya dari seri ini?\n1  .5  .25  .125  ......',
    type: 'isian',
    correctAnswer: '0.0625',
    category: 'Deret',
  },
  {
    id: 38,
    question: 'Bentuk geometris ini dapat dibagi oleh suatu garis lurus menjadi dua bagian yang dapat disatukan dengan suatu cara hingga membentuk bujur sangkar yang sempurna. Tuliskan dua angka yang dihubungkan (misal: 6-14) sebagai jawaban.',
    type: 'isian',
    correctAnswer: '6-14',
    category: 'Visual',
    image: '/wpt-images/q38.png',
  },
  {
    id: 39,
    question: 'Apakah arti dari kalimat berikut:\n\nSebuah sapu yang baru menyapu dengan bersih. Sepatu yang sudah lama sifatnya makin lunak.',
    type: 'pilihan_ganda',
    options: ['sama', 'berlawanan', 'tidak sama atau berlawanan'],
    correctAnswer: '1',
    category: 'Logika',
  },
  {
    id: 40,
    question: 'Berapa duplikasi dari pasangan kata berikut ini?\n\nRexford, J.D. - Rockford, J.D.\nSingleton, M.O. - Simbleten, M.O.\nRichards, W.E. - Richad, W.E.\nSiegel, A.B. - Seigel, A.B.\nWood, A.O. - Wood, A.O.',
    type: 'isian',
    correctAnswer: '1',
    category: 'Deret',
  },
  {
    id: 41,
    question: 'Dua dari peribahasa ini memiliki makna yang serupa. Manakah itu? (Tulis dua angka)\n1. Anda tidak dapat membuat dompet sutra dari kuping babi betina.\n2. Orang yang mencuri telur akan mencuri sapi.\n3. Batu yang berguling tidak akan mengumpulkan lumut.\n4. Anda tidak mungkin menghancurkan kapal yang sudah rusak.\n5. Ini ketidakmungkinan yang terjadi.',
    type: 'isian',
    correctAnswer: '1 DAN 4',
    category: 'Logika',
  },
  {
    id: 42,
    question: 'Gambar geometris ini dapat dibagi dengan garis lurus menjadi dua bagian yang dapat disatukan untuk membentuk sebuah bujur sangkar yang sempurna. Tuliskan dua angka yang dihubungkan sebagai jawaban.',
    type: 'isian',
    correctAnswer: '10-20',
    category: 'Visual',
    image: '/wpt-images/q42.png',
  },
  {
    id: 43,
    question: 'Dalam kelompok angka berikut ini, manakah angka yang terkecil?\n10 – 1 – .999 – .33 – 11',
    type: 'isian',
    correctAnswer: '.33',
    category: 'Deret',
  },
  {
    id: 44,
    question: 'Apakah makna dari kalimat berikut:\n\nTidak ada orang jujur meminta maaf atas kejujurannya. Kejujuran dihormati dan layak pujian.',
    type: 'pilihan_ganda',
    options: ['sama', 'berlawanan', 'tidak sama atau berlawanan'],
    correctAnswer: '1',
    category: 'Vocab',
  },
  {
    id: 45,
    question: 'Dengan harga 1.80 dolar, seorang grosir membeli satu kardus buah yang berisi 12 lusin. Ia tahu dua lusin akan busuk sebelum dia menjualnya. Dengan harga berapa per lusin dia harus menjual jeruk itu untuk mendapat 1/3 dari harga seluruhnya?',
    type: 'isian',
    correctAnswer: '0.27',
    category: 'Aritmatika',
  },
  {
    id: 46,
    question: 'Dalam rangkaian kata berikut ini, manakah kata yang berbeda dari yang lainnya?',
    type: 'pilihan_ganda',
    options: ['koloni', 'perkawanan', 'kawanan', 'kru', 'konstelasi'],
    correctAnswer: '5',
    category: 'Logika',
  },
  {
    id: 47,
    question: 'Anggaplah dua pernyataan pertama ini benar. Apakah pernyataan terakhir:\n\nOrang besar dibodohi. Saya dibodohi. Saya adalah orang besar.',
    type: 'pilihan_ganda',
    options: ['benar', 'salah', 'tidak tahu'],
    correctAnswer: '2',
    category: 'Logika',
  },
  {
    id: 48,
    question: 'Tiga orang membentuk kemitraan dan setuju membagi keuntungan secara rata. X menginvestasi 4.500 dolar, Y sebesar 3.500 dolar, dan Z sebesar 2.000 dolar. Jika keuntungan mencapai 1.500 dolar, lebih kurang berapa yang akan diperoleh X dibanding jika keuntungan dibagi berdasarkan besarnya investasi?',
    type: 'isian',
    correctAnswer: '175',
    category: 'Aritmatika',
  },
  {
    id: 49,
    question: 'Empat dari 5 bagian ini dapat digabungkan untuk membuat segitiga. Manakah keempat gambar ini?',
    type: 'isian',
    correctAnswer: '1,2,4,5',
    category: 'Visual',
    image: '/wpt-images/q49.png',
  },
  {
    id: 50,
    question: 'Untuk mencetak sebuah artikel berisi 30.000 kata, sebuah percetakan memutuskan untuk memakai dua ukuran jenis. Dengan menggunakan tipe yang lebih besar, sebuah halaman tercetak akan memuat 1.200 kata. Dengan tipe yang lebih kecil, sebuah halaman memuat 1.500 kata. Artikel ini masuk dalam 22 halaman di majalah. Berapa banyak halaman yang dibutuhkan untuk tipe yang lebih kecil?',
    type: 'isian',
    correctAnswer: '18',
    category: 'Aritmatika',
  },
];

export const WPT_DURATION_MINUTES = 20;
export const WPT_TOTAL_QUESTIONS = 50;

export const WPT_BENCHMARKS: Record<string, { min: number; ideal: string; max: number }> = {
  'PLA (Paralegal/Legal Admin)': { min: 26, ideal: '28-35', max: 50 },
  'Legal Officer (LO)': { min: 23, ideal: '25-32', max: 50 },
  'Marketing Staff': { min: 20, ideal: '22-27', max: 45 },
  'CRM Staff': { min: 18, ideal: '20-25', max: 40 },
  'Internship': { min: 15, ideal: '16-22', max: 35 },
};
