version: '3.8'

services:
  recruit-el-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruit-el-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
